// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multimedia.Infrastructure.Persistence;

#nullable disable

namespace Multimedia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727064919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Multimedia.Domain.Models.Auditoria", b =>
                {
                    b.Property<Guid>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioDb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditoriaId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Biblioteca", b =>
                {
                    b.Property<Guid>("BibliotecaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ContenidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EsFavorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BibliotecaId");

                    b.HasIndex("ContenidoId");

                    b.HasIndex("UsuarioId", "ContenidoId")
                        .IsUnique();

                    b.ToTable("Biblioteca", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Artista", b =>
                {
                    b.Property<Guid>("ArtistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SegundoApellido")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("");

                    b.HasKey("ArtistaId");

                    b.ToTable("Artistas", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Clasificacion", b =>
                {
                    b.Property<Guid>("ClasificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ClasificacionId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Clasificacion", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Director", b =>
                {
                    b.Property<Guid>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SegundoApellido")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("");

                    b.HasKey("DirectorId");

                    b.ToTable("Directores", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Editorial", b =>
                {
                    b.Property<Guid>("EditorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EditorialId");

                    b.ToTable("Editoriales", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.EstadoContenido", b =>
                {
                    b.Property<Guid>("EstadoContenidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EstadoContenidoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoContenido", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Formato", b =>
                {
                    b.Property<Guid>("FormatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FormatoId");

                    b.ToTable("Formatos", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Genero", b =>
                {
                    b.Property<Guid>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Idioma", b =>
                {
                    b.Property<Guid>("IdiomaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("PeliculaContenidoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdiomaId");

                    b.HasIndex("PeliculaContenidoId");

                    b.ToTable("Idiomas", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Plataforma", b =>
                {
                    b.Property<Guid>("PlataformaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PlataformaId");

                    b.ToTable("Plataformas", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Rol", b =>
                {
                    b.Property<Guid>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.TipoContenido", b =>
                {
                    b.Property<Guid>("TipoContenidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TipoContenidoId");

                    b.ToTable("TiposContenidos", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Contenido", b =>
                {
                    b.Property<Guid>("ContenidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<Guid>("ClasificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("EstadoContenidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateOnly?>("FechaLanzamiento")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FormatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeneroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdiomaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Portada")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TipoContenidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UsuarioActualizacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContenidoId");

                    b.HasIndex("ClasificacionId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("EstadoContenidoId");

                    b.HasIndex("FormatoId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("IdiomaId");

                    b.HasIndex("TipoContenidoId");

                    b.HasIndex("Titulo");

                    b.HasIndex("UsuarioActualizacionId");

                    b.ToTable("Contenido", "Multimedia", t =>
                        {
                            t.HasCheckConstraint("CK_Contenido_Anio", "[Anio] >= 1800 AND [Anio] <= YEAR(SYSDATETIME()) + 5");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTimeOffset?>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Correo")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Correo"), new[] { "PasswordHash", "RolId", "EsActivo" });

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", "Multimedia");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Libro", b =>
                {
                    b.HasBaseType("Multimedia.Domain.Models.Dominio.Contenido");

                    b.Property<Guid>("EditorialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumeroPaginas")
                        .HasColumnType("int");

                    b.HasIndex("EditorialId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Libro", "Multimedia", t =>
                        {
                            t.HasCheckConstraint("CK_Contenido_Anio", "[Anio] >= 1800 AND [Anio] <= YEAR(SYSDATETIME()) + 5");
                        });
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Musica", b =>
                {
                    b.HasBaseType("Multimedia.Domain.Models.Dominio.Contenido");

                    b.Property<string>("Album")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Musica", "Multimedia", t =>
                        {
                            t.HasCheckConstraint("CK_Contenido_Anio", "[Anio] >= 1800 AND [Anio] <= YEAR(SYSDATETIME()) + 5");

                            t.HasCheckConstraint("CK_Musica_Duracion", "\"DuracionMinutos\" > 0");
                        });
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Pelicula", b =>
                {
                    b.HasBaseType("Multimedia.Domain.Models.Dominio.Contenido");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.HasIndex("DirectorId");

                    b.ToTable("Peliculas", "Multimedia", t =>
                        {
                            t.HasCheckConstraint("CK_Contenido_Anio", "[Anio] >= 1800 AND [Anio] <= YEAR(SYSDATETIME()) + 5");
                        });
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Videojuego", b =>
                {
                    b.HasBaseType("Multimedia.Domain.Models.Dominio.Contenido");

                    b.Property<bool>("EsMultijugador")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlataformaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PlataformaId");

                    b.ToTable("VideoJuegos", "Multimedia", t =>
                        {
                            t.HasCheckConstraint("CK_Contenido_Anio", "[Anio] >= 1800 AND [Anio] <= YEAR(SYSDATETIME()) + 5");
                        });
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Biblioteca", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Dominio.Contenido", "Contenido")
                        .WithMany()
                        .HasForeignKey("ContenidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contenido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Idioma", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Dominio.Pelicula", null)
                        .WithMany("Idiomas")
                        .HasForeignKey("PeliculaContenidoId");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Contenido", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Catalogo.Clasificacion", "Clasificacion")
                        .WithMany()
                        .HasForeignKey("ClasificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.EstadoContenido", "EstadoContenido")
                        .WithMany()
                        .HasForeignKey("EstadoContenidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.Formato", "Formato")
                        .WithMany()
                        .HasForeignKey("FormatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.Idioma", "Idioma")
                        .WithMany()
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.TipoContenido", "TipoContenido")
                        .WithMany()
                        .HasForeignKey("TipoContenidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clasificacion");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("EstadoContenido");

                    b.Navigation("Formato");

                    b.Navigation("Genero");

                    b.Navigation("Idioma");

                    b.Navigation("TipoContenido");

                    b.Navigation("UsuarioActualizacion");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Usuario", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Catalogo.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Libro", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Dominio.Contenido", null)
                        .WithOne()
                        .HasForeignKey("Multimedia.Domain.Models.Dominio.Libro", "ContenidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.Editorial", "Editorial")
                        .WithMany("Libros")
                        .HasForeignKey("EditorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Musica", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Catalogo.Artista", "Artista")
                        .WithMany("Albumes")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Dominio.Contenido", null)
                        .WithOne()
                        .HasForeignKey("Multimedia.Domain.Models.Dominio.Musica", "ContenidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Pelicula", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Dominio.Contenido", null)
                        .WithOne()
                        .HasForeignKey("Multimedia.Domain.Models.Dominio.Pelicula", "ContenidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Videojuego", b =>
                {
                    b.HasOne("Multimedia.Domain.Models.Dominio.Contenido", null)
                        .WithOne()
                        .HasForeignKey("Multimedia.Domain.Models.Dominio.Videojuego", "ContenidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multimedia.Domain.Models.Catalogo.Plataforma", null)
                        .WithMany()
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Artista", b =>
                {
                    b.Navigation("Albumes");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Editorial", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Catalogo.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Multimedia.Domain.Models.Dominio.Pelicula", b =>
                {
                    b.Navigation("Idiomas");
                });
#pragma warning restore 612, 618
        }
    }
}
